[package]
name = "wind-skills"
description = """
skills ability for windai
"""
edition.workspace = true
version.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]

serde.workspace = true
serde_json.workspace = true
yaml-rust2.workspace = true
schemars.workspace = true
thiserror.workspace = true
log.workspace = true

[dev-dependencies]
