[package]
name = "wind-http"
description = """
windai http server
"""
edition.workspace = true
version.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]

wind-mcp = { path = "../mcp" }
wind-ai = { path = "../ai" }
wind-rule = { path = "../rule" }
wind-core = { path = "../core" }

tokio.workspace = true
tokio-util.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
futures.workspace = true

axum = { version = "0.8" }
tower = { version = "0.5", features = ["full"] }
tower-http = { version = "0.7", features = ["trace", "timeout", "request-id", "set-header", "cors"] }
utoipa = { workspace = true, features = ["axum_extras"] }
utoipa-swagger-ui = { version = "9", features = ["axum"] }
tokio-stream = { version = "0.1", features = ["sync"] }

thiserror.workspace = true
log.workspace = true
env_logger.workspace = true

[dev-dependencies]
sqlx = { workspace = true, features = ["sqlite"] }
