[package]
name = "windai-chat"
description = """
This crate provides the LLM chat ability.
"""
edition.workspace = true
version.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
reqwest.workspace = true
strum.workspace = true
serde.workspace = true
serde_json.workspace = true
derive_builder.workspace = true
futures.workspace = true
bytes.workspace = true
# dotenvy.workspace = true
thiserror.workspace = true
async-stream.workspace = true
# rusqlite.workspace = true
# dirs.workspace = true
log.workspace = true
url.workspace = true
chrono.workspace = true
# windai-domain.workspace = true

[dev-dependencies]
env_logger.workspace = true
tokio.workspace = true
