[package]
name = "wind-core"
description = "Core orchestration for Wind AI"
edition.workspace = true
version.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
wind-mcp = { path = "../mcp" }
wind-ai = { path = "../ai" }
wind-js = { path = "../js" }

reqwest.workspace = true
strum.workspace = true
serde.workspace = true
serde_json.workspace = true
derive_builder.workspace = true
futures.workspace = true
bytes.workspace = true
thiserror.workspace = true
async-stream.workspace = true
log.workspace = true
url.workspace = true
chrono.workspace = true
rmcp.workspace = true
schemars.workspace = true
tokio.workspace = true
sqlx.workspace = true
rquickjs.workspace = true
dirs.workspace = true

[dev-dependencies]
dotenvy.workspace = true
env_logger.workspace = true
test-case.workspace = true
